### ISSUE TITLE
Dont want awsS3Key

### ISSUE THREAD

**Issue by bobybobybob** [avirtuos/pi_zero#1]
Feature Request

write Data only on local device so i can work with it with bash FTP Upload, own Webserver in Intranet etc.

Dont want a account on Amazon or other 3rdParty Companys

**Comment by avirtuos** [comment]
That's reasonable. I'll up this weekend.

**Comment by avirtuos** [comment]
Actually would you like me to add an FTP target or perhaps even run a local webserver from within Python so you can host the image directly.

**Comment by bobybobybob** [comment]
Both would be cool and usefull for all. Maybe on the first line in script a option who user can chose the way.

**Comment by avirtuos** [comment]
I haven't forgotten about this, just ran into some other things I had to do. I'm now shooting to do this next week while I'm off work.

**Comment by avirtuos** [comment]
Actually, I just took a quick look and this is now completed.

You can disable S3 uploads by simply omitting the AWS specific environment variables. 

I also added the ability to use an embedded http server. All you need to do is specify the port you want the server to run on and collectd.py will start a python web server in a separate thread and host the two graphs it generates as well as a simple landing page that has the two graphs.

Let me know if you face any issues but I've updated my 3 nodes to the latest commit and tested with/without AWS S3 and the embedded web server.

[This is the commit that included these changes.](https://github.com/avirtuos/pi_zero/commit/fe0e3d31001afa98a5e5cffd785b779a8ca37b22)
